### ISSUE TITLE
RoadMap of obvious

### ISSUE THREAD

**Issue by run-nan** [obvious-js/obvious#27]
# 😉  RoadMap of obvious

## Infrastructure
- [x] monorepo with lerna

## Pacakges
- [x] **@obvious-js/core**
  - [x] feature: reactive state with @vue/reactivity
  - [x] feature: event proxy
- [ ] **@obvious-js/react**: the react binding for obvious-js
- [ ] **@obvious-js/vue**: the vue binding for obvious-js
- [ ] **@obvious-js/pro**: the framework to provide standard usage for obvious

## Ecosystem
- [x] import-html middleware
- [ ] jsdelivr loader middleware
- [ ] sandbox middleware

## Document
- [ ] new document with vuepress
- [ ] new README

## Articles
- [ ] Chinese blogs on JUEJIN to introduce obvious

**Comment by xxbld** [comment]
期待早日用于生产！
admin模板示例可以用这个开发嘛
https://github.com/anncwb/vue-vben-admin

**Comment by itmanyong** [comment]
期待早日可用生产

**Comment by run-nan** [comment]
你好，我已收到您的邮件

**Comment by bvcvb** [comment]
期待！~
